services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: pentavalue-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: pentavalue-nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 
